FROM mcr.microsoft.com/mssql/server:2022-latest

USER root

ENV ACCEPT_EULA=Y
ENV MSSQL_PID=Express
ENV MSSQL_MEMORY_LIMIT_MB=1024
ENV HOME=/var/opt/mssql
ENV MSSQL_DUMP_DIR=/tmp
ENV MSSQL_ENABLE_HADR=0
ENV MSSQL_AGENT_ENABLED=false

RUN mkdir -p /var/opt/mssql/data \
    /var/opt/mssql/log \
    /var/opt/mssql/secrets \
    /var/opt/mssql/.system \
    /tmp/mssql-dumps \
    /.system \
    && chown -R 10001:0 /var/opt/mssql /tmp/mssql-dumps /.system \
    && chmod -R 775 /var/opt/mssql /tmp/mssql-dumps /.system

USER 10001

WORKDIR /var/opt/mssql

ENTRYPOINT ["/opt/mssql/bin/sqlservr"]