FROM mcr.microsoft.com/mssql/server:2022-latest

USER root

ENV ACCEPT_EULA=Y
ENV MSSQL_PID=Express
ENV MSSQL_MEMORY_LIMIT_MB=1024
ENV HOME=/var/opt/mssql

RUN mkdir -p /var/opt/mssql \
    && chown -R 10001:0 /var/opt/mssql \
    && chmod -R g=u /var/opt/mssql

USER 10001

WORKDIR /var/opt/mssql

ENTRYPOINT ["/opt/mssql/bin/sqlservr"]
