FROM mcr.microsoft.com/mssql/server:2022-latest

USER root

ENV ACCEPT_EULA=Y
ENV MSSQL_PID=Express
ENV MSSQL_MEMORY_LIMIT_MB=1024
ENV HOME=/var/opt/mssql
ENV MSSQL_DUMP_DIR=/tmp
ENV MSSQL_AGENT_ENABLED=false

COPY railway-mssql-entrypoint.sh /usr/local/bin/railway-mssql-entrypoint.sh

RUN chmod +x /usr/local/bin/railway-mssql-entrypoint.sh

WORKDIR /var/opt/mssql

ENTRYPOINT ["/usr/local/bin/railway-mssql-entrypoint.sh"]
